version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: creatorx
      POSTGRES_PASSWORD: creatorx
      POSTGRES_DB: creatorx
    ports:
      - "5432:5432"
    volumes:
      - creatorx-data:/var/lib/postgresql/data

volumes:
  creatorx-data:
